### PR TITLE
add link slack

### PR DESCRIPTION
**Pull request by camilledel**

### CODE REVIEW

**Comment by abelards** [comment]
:+1:

**Comment by tibastral** [comment]
+1

**Comment by abelards** [comment]
Merged! Thanks @camilledel <3
How is it put in prod BTW?
Cheers,

**Comment by tibastral** [comment]
Simon has the access :) he can give you the access

- Thibaut

**Comment by simonc** [comment]
@abelards invited you on your gmail address ;)

**Pull request merged**
