### PR TITLE
Update Readme; Update ruby version 2.3.3; to allow Heroku deployment;

### PR DESCRIPTION
**Pull request by MichaelDimmitt**
Upgraded to ruby version 2.3.3; allows Heroku deployment;
Updated Readme.md; install instructions; Heroku deploy instructions;

Maintainer needs to check that updating Ruby, Devise, and Rails did not cause the loss of any features. However, worked on my environment.

Hope someone finds this helpful. Nice Website. 😄

### CODE REVIEW

**Comment by abelards** [comment]
Hi and thanks for the contrib! Sadly we took waaaay too long to review these.
We might have conflicts with PRs #29 #15 and #16 -- let's try to close these PRs :)
Thanks again!

**Comment by nicolasleger** [comment]
Might add a `.ruby-version` file like https://github.com/parisrb/rubyparis.org/pull/15/files

**Comment by MichaelDimmitt** [comment]
@nicolasleger, sure I can add that in upon request.

@abelards, would it help if I rebased master to get the branch up to date with master?

**Comment by MichaelDimmitt** [comment]
putting this in the readme.
ruby_paris_readme_image

**Comment by yannski** [comment]
Hi @MichaelDimmitt sorry for the loooooong delay to take care of this PR. This project now runs under Ruby 2.6.4 and Rails 5. Therefore I will now close this PR. We would gladly accept another PR with only the README instructions.

**Pull request closed without merging**
